public class anotherassignment {
    
    public static String hello(String name){
        if(name == 'Abhisek'){
            return 'Abhisek Maiti';
                }
          return 'Sorry';
    }
    
    @testvisible
    private List<string> alltrainee(String name){
        List<string> allname = new List<string>();
        allname.add('Rituja');
        allname.add('Anurag');
        allname.add(name);
        return allname;
    }

}